# numa_ultralytics ğŸš€ AGPL-3.0 License - https://numa_ultralytics.com/license

blank_issues_enabled: true
contact_links:
  - name: ğŸ“„ Docs
    url: https://docs.numa_ultralytics.com/
    about: Full numa_ultralytics YOLO Documentation
  - name: ğŸ’¬ Forum
    url: https://community.numa_ultralytics.com/
    about: Ask on numa_ultralytics Community Forum
  - name: ğŸ§ Discord
    url: https://numa_ultralytics.com/discord
    about: Ask on numa_ultralytics Discord
  - name: âŒ¨ï¸ Reddit
    url: https://reddit.com/r/numa_ultralytics
    about: Ask on numa_ultralytics Subreddit
