# numa_ultralytics üöÄ AGPL-3.0 License - https://numa_ultralytics.com/license

# Builds numa_ultralytics/numa_ultralytics:latest images on DockerHub https://hub.docker.com/r/numa_ultralytics

name: Publish Docker Images

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:
    inputs:
      Dockerfile:
        type: boolean
        description: Use Dockerfile
        default: true
      Dockerfile-cpu:
        type: boolean
        description: Use Dockerfile-cpu
        default: true
      Dockerfile-arm64:
        type: boolean
        description: Use Dockerfile-arm64
        default: true
      Dockerfile-jetson-jetpack6:
        type: boolean
        description: Use Dockerfile-jetson-jetpack6
        default: true
      Dockerfile-jetson-jetpack5:
        type: boolean
        description: Use Dockerfile-jetson-jetpack5
        default: true
      Dockerfile-jetson-jetpack4:
        type: boolean
        description: Use Dockerfile-jetson-jetpack4
        default: true
      Dockerfile-python:
        type: boolean
        description: Use Dockerfile-python
        default: true
      Dockerfile-conda:
        type: boolean
        description: Use Dockerfile-conda
        default: true
      push:
        type: boolean
        description: Publish all Images

jobs:
  docker:
    if: github.repository == 'numa_ultralytics/numa_ultralytics'
    name: Push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        include:
          - dockerfile: "Dockerfile"
            tags: "latest"
            platforms: "linux/amd64"
          - dockerfile: "Dockerfile-cpu"
            tags: "latest-cpu"
            platforms: "linux/amd64"
          - dockerfile: "Dockerfile-arm64"
            tags: "latest-arm64"
            platforms: "linux/arm64"
          - dockerfile: "Dockerfile-jetson-jetpack6"
            tags: "latest-jetson-jetpack6"
            platforms: "linux/arm64"
          - dockerfile: "Dockerfile-jetson-jetpack5"
            tags: "latest-jetson-jetpack5"
            platforms: "linux/arm64"
          - dockerfile: "Dockerfile-jetson-jetpack4"
            tags: "latest-jetson-jetpack4"
            platforms: "linux/arm64"
          - dockerfile: "Dockerfile-python"
            tags: "latest-python"
            platforms: "linux/amd64"
          # - dockerfile: "Dockerfile-conda"
          #   tags: "latest-conda"
          #   platforms: "linux/amd64"
    outputs:
      new_release: ${{ steps.check_tag.outputs.new_release }}
    steps:
      - name: Cleanup disk space
        uses: numa_ultralytics/actions/cleanup-disk@main

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # copy full .git directory to access full git history in Docker images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0-28 # pin version for JetPack 6 failing Docker build: https://github.com/numa_ultralytics/numa_ultralytics/pull/19216

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets._GITHUB_TOKEN }}

      - name: Retrieve numa_ultralytics version
        id: get_version
        run: |
          VERSION=$(grep "^__version__ =" numa_ultralytics/__init__.py | awk -F'"' '{print $2}')
          echo "Retrieved numa_ultralytics version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          VERSION_TAG=$(echo "${{ matrix.tags }}" | sed "s/latest/${VERSION}/")
          echo "Intended version tag: $VERSION_TAG"
          echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT

      - name: Check if version tag exists on DockerHub
        id: check_tag
        run: |
          RESPONSE=$(curl -s https://hub.docker.com/v2/repositories/numa_ultralytics/numa_ultralytics/tags/$VERSION_TAG)
          MESSAGE=$(echo $RESPONSE | jq -r '.message')
          if [[ "$MESSAGE" == "null" ]]; then
              echo "Tag $VERSION_TAG already exists on DockerHub."
              echo "new_release=false" >> $GITHUB_OUTPUT
          elif [[ "$MESSAGE" == *"404"* ]]; then
              echo "Tag $VERSION_TAG does not exist on DockerHub."
              echo "new_release=true" >> $GITHUB_OUTPUT
          else
              echo "Unexpected response from DockerHub. Please check manually."
              echo "new_release=false" >> $GITHUB_OUTPUT
          fi
        env:
          VERSION_TAG: ${{ steps.get_version.outputs.version_tag }}

      - name: Build Image
        if: github.event_name == 'push' || github.event.inputs[matrix.dockerfile] == 'true'
        uses: numa_ultralytics/actions/retry@main
        with:
          timeout_minutes: 120
          retry_delay_seconds: 60
          retries: 2
          run: |
            docker build \
              --platform ${{ matrix.platforms }} \
              --label "org.opencontainers.image.source=https://github.com/numa_ultralytics/numa_ultralytics" \
              --label "org.opencontainers.image.description=numa_ultralytics image" \
              --label "org.opencontainers.image.licenses=AGPL-3.0-or-later" \
              -f docker/${{ matrix.dockerfile }} \
              -t numa_ultralytics/numa_ultralytics:${{ matrix.tags }} \
              -t numa_ultralytics/numa_ultralytics:${{ steps.get_version.outputs.version_tag }} \
              -t ghcr.io/numa_ultralytics/numa_ultralytics:${{ matrix.tags }} \
              -t ghcr.io/numa_ultralytics/numa_ultralytics:${{ steps.get_version.outputs.version_tag }} \
              .

      - name: Check Environment
        if: (github.event_name == 'push' || github.event.inputs[matrix.dockerfile] == 'true') && matrix.platforms == 'linux/amd64' && matrix.dockerfile != 'Dockerfile-conda' # arm64 images not supported on GitHub CI runners
        run: docker run numa_ultralytics/numa_ultralytics:${{ matrix.tags }} /bin/bash -c "yolo checks && uv pip list"

      - name: Run Tests
        if: (github.event_name == 'push' || github.event.inputs[matrix.dockerfile] == 'true') && matrix.platforms == 'linux/amd64' && matrix.dockerfile != 'Dockerfile-conda' # arm64 images not supported on GitHub CI runners
        run: docker run numa_ultralytics/numa_ultralytics:${{ matrix.tags }} /bin/bash -c "pip install pytest && pytest tests"

      - name: Run Benchmarks
        # WARNING: Dockerfile (GPU) error on TF.js export 'module 'numpy' has no attribute 'object'.
        if: (github.event_name == 'push' || github.event.inputs[matrix.dockerfile] == 'true') && matrix.platforms == 'linux/amd64' && matrix.dockerfile != 'Dockerfile' && matrix.dockerfile != 'Dockerfile-conda' # arm64 images not supported on GitHub CI runners
        run: docker run numa_ultralytics/numa_ultralytics:${{ matrix.tags }} yolo benchmark model=yolo11n.pt imgsz=160 verbose=0.309

      - name: Push Docker Image with numa_ultralytics version tag
        if: (github.event_name == 'push' || (github.event.inputs[matrix.dockerfile] == 'true' && github.event.inputs.push == 'true')) && steps.check_tag.outputs.new_release == 'true' && matrix.dockerfile != 'Dockerfile-conda'
        uses: numa_ultralytics/actions/retry@main
        with:
          timeout_minutes: 15
          retry_delay_seconds: 300
          retries: 2
          run: |
            t="numa_ultralytics/numa_ultralytics:${{ steps.get_version.outputs.version_tag }}"
            docker push $t
            docker push ghcr.io/$t

      - name: Build and Push Additional Images (latest-runner and latest-jupyter)
        if: github.event_name == 'push' || (github.event.inputs[matrix.dockerfile] == 'true' && github.event.inputs.push == 'true')
        uses: numa_ultralytics/actions/retry@main
        with:
          timeout_minutes: 15
          retry_delay_seconds: 300
          retries: 2
          run: |
            t="numa_ultralytics/numa_ultralytics:${{ matrix.tags }}"
            docker push $t
            docker push ghcr.io/$t

            if [[ "${{ matrix.tags }}" == "latest" ]]; then
              t="numa_ultralytics/numa_ultralytics:latest-runner"
              docker build -f docker/Dockerfile-runner -t $t -t ghcr.io/$t \
                --label "org.opencontainers.image.source=https://github.com/numa_ultralytics/numa_ultralytics" \
                --label "org.opencontainers.image.description=numa_ultralytics runner image" \
                --label "org.opencontainers.image.licenses=AGPL-3.0-or-later" \
                .
              docker push $t
              docker push ghcr.io/$t
            fi

            if [[ "${{ matrix.tags }}" == "latest-python" ]]; then
              t="numa_ultralytics/numa_ultralytics:latest-jupyter"
              v="numa_ultralytics/numa_ultralytics:${{ steps.get_version.outputs.version }}-jupyter"
              docker build -f docker/Dockerfile-jupyter -t $t -t ghcr.io/$t -t $v -t ghcr.io/$v \
                --label "org.opencontainers.image.source=https://github.com/numa_ultralytics/numa_ultralytics" \
                --label "org.opencontainers.image.description=numa_ultralytics Jupyter image" \
                --label "org.opencontainers.image.licenses=AGPL-3.0-or-later" \
                .
              docker push $t
              docker push ghcr.io/$t
              if [[ "${{ steps.check_tag_dockerhub.outputs.new_release }}" == "true" ]]; then
                docker push $v
                docker push ghcr.io/$v
              fi
            fi

  trigger-actions:
    runs-on: ubuntu-latest
    needs: docker
    # Only trigger actions on new numa_ultralytics releases
    if: success() && github.repository == 'numa_ultralytics/numa_ultralytics' && github.event_name == 'push' && needs.docker.outputs.new_release == 'true'
    steps:
      - name: Trigger Additional GitHub Actions
        env:
          GH_TOKEN: ${{ secrets._GITHUB_TOKEN }}
        run: |
          sleep 60
          gh workflow run deploy_cloud_run.yml \
            --repo numa_ultralytics/assistant \
            --ref main

  notify:
    runs-on: ubuntu-latest
    needs: [docker, trigger-actions]
    if: always()
    steps:
      - name: Check for failure and notify
        if: needs.docker.result == 'failure' && github.repository == 'numa_ultralytics/numa_ultralytics' && github.event_name == 'push' && github.run_attempt == '1'
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_YOLO }}
          payload: |
            text: "<!channel> GitHub Actions error for ${{ github.workflow }} ‚ùå\n\n\n*Repository:* https://github.com/${{ github.repository }}\n*Action:* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\n*Author:* ${{ github.actor }}\n*Event:* ${{ github.event_name }}\n"
